// ─── Dashboard Stats ──────────────────────────────────────────────────────────

export const dashboardStats = [
  { id: "s1", label: "Active Consents", value: "1,284", change: "+12", trend: "up", accent: "amber" },
  { id: "s2", label: "Open Escalations", value: "23", change: "-4", trend: "down", accent: "rose" },
  { id: "s3", label: "Audit Records (30d)", value: "8,491", change: "+340", trend: "up", accent: "cyan" },
  { id: "s4", label: "Drift Incidents", value: "7", change: "+2", trend: "up", accent: "violet" },
  { id: "s5", label: "Pending Promotions", value: "41", change: "+9", trend: "up", accent: "emerald" },
  { id: "s6", label: "Compliance Rate", value: "97.3%", change: "+0.4%", trend: "up", accent: "emerald" },
];

export const weeklyActivity = [
  { day: "Mon", actions: 148, resolved: 130 },
  { day: "Tue", actions: 212, resolved: 190 },
  { day: "Wed", actions: 165, resolved: 155 },
  { day: "Thu", actions: 290, resolved: 260 },
  { day: "Fri", actions: 238, resolved: 220 },
  { day: "Sat", actions: 89, resolved: 82 },
  { day: "Sun", actions: 52, resolved: 50 },
];

// ─── Alerts ────────────────────────────────────────────────────────────────────

export const alerts = [
  {
    id: "ALT-9921",
    severity: "critical",
    title: "Identity anchor mismatch — TM Registry #4482",
    description: "Trademark registry record conflicts with court filing identity. Immediate review required.",
    module: "Trademark",
    assignee: "Sarah Okonkwo",
    time: "2 min ago",
    status: "open",
  },
  {
    id: "ALT-9920",
    severity: "high",
    title: "Consent expiry approaching — Contract GV-2281",
    description: "Active consent window closes in 48 hours with no renewal initiated.",
    module: "Consent",
    assignee: "Marcus Chen",
    time: "18 min ago",
    status: "open",
  },
  {
    id: "ALT-9918",
    severity: "high",
    title: "Policy drift detected — Compliance Framework v3",
    description: "3 governed records reference deprecated policy version. Remediation workflow triggered.",
    module: "Compliance",
    assignee: "Unassigned",
    time: "1 hr ago",
    status: "reviewing",
  },
  {
    id: "ALT-9914",
    severity: "medium",
    title: "Role permission escalation request",
    description: "Operations user D. Farouk requested Trust Admin elevation. Pending approval.",
    module: "Admin",
    assignee: "Lydia Martins",
    time: "3 hr ago",
    status: "reviewing",
  },
  {
    id: "ALT-9910",
    severity: "low",
    title: "Documentation registry sync lag",
    description: "Codex ledger export is 22 minutes behind real-time. Monitoring.",
    module: "Codex",
    assignee: "System",
    time: "5 hr ago",
    status: "monitoring",
  },
  {
    id: "ALT-9905",
    severity: "critical",
    title: "Unauthorized promotion attempt blocked",
    description: "Non-privileged user attempted to promote draft record TM-7741 without approval chain.",
    module: "Trademark",
    assignee: "Sarah Okonkwo",
    time: "Yesterday",
    status: "resolved",
  },
];

// ─── Consent Records ──────────────────────────────────────────────────────────

export const consentRecords = [
  {
    id: "CON-4491",
    subject: "Meridian Health Group",
    type: "Data Processing Agreement",
    status: "active",
    granted: "2025-11-15",
    expires: "2026-11-14",
    scope: ["PII Processing", "Cross-border Transfer", "Analytics"],
    owner: "Sarah Okonkwo",
    lastModified: "2026-03-02",
    version: "v3.1",
  },
  {
    id: "CON-4488",
    subject: "Vantara Logistics Ltd",
    type: "Trademark License",
    status: "active",
    granted: "2025-09-01",
    expires: "2026-08-31",
    scope: ["Regional Use", "Sub-licensing"],
    owner: "Marcus Chen",
    lastModified: "2026-04-10",
    version: "v2.0",
  },
  {
    id: "CON-4477",
    subject: "Crestline Partners",
    type: "Trust Agreement",
    status: "expiring",
    granted: "2024-06-01",
    expires: "2026-06-01",
    scope: ["Financial Data", "Identity Anchor"],
    owner: "Lydia Martins",
    lastModified: "2026-05-01",
    version: "v1.4",
  },
  {
    id: "CON-4462",
    subject: "Optic Wave Media",
    type: "Data Processing Agreement",
    status: "under-review",
    granted: "2026-01-20",
    expires: "2027-01-19",
    scope: ["Content Analytics", "User Profiling"],
    owner: "Sarah Okonkwo",
    lastModified: "2026-05-10",
    version: "v1.0",
  },
  {
    id: "CON-4440",
    subject: "NovaBridge Corp",
    type: "Compliance Obligation",
    status: "active",
    granted: "2025-03-15",
    expires: "2027-03-14",
    scope: ["Regulatory Reporting", "Audit Rights"],
    owner: "Marcus Chen",
    lastModified: "2025-12-01",
    version: "v2.2",
  },
  {
    id: "CON-4410",
    subject: "Ascend Realty Group",
    type: "Trust Agreement",
    status: "revoked",
    granted: "2024-02-10",
    expires: "2025-02-09",
    scope: ["Identity Anchor"],
    owner: "Lydia Martins",
    lastModified: "2025-02-09",
    version: "v1.1",
  },
  {
    id: "CON-4390",
    subject: "Kestrel Finance",
    type: "Trademark License",
    status: "draft",
    granted: "—",
    expires: "—",
    scope: ["Logo Usage", "Digital"],
    owner: "Unassigned",
    lastModified: "2026-05-08",
    version: "v0.3",
  },
];

// ─── Codex / Audit Ledger ─────────────────────────────────────────────────────

export const codexEntries = [
  {
    id: "CDX-00441",
    timestamp: "2026-05-11 09:42:17",
    actor: "Sarah Okonkwo",
    role: "Trust Admin",
    action: "RECORD_PROMOTED",
    target: "CON-4491",
    module: "Consent",
    hash: "a3f9b21c",
    outcome: "success",
    notes: "Promoted to official status after full approval chain.",
  },
  {
    id: "CDX-00440",
    timestamp: "2026-05-11 09:38:04",
    actor: "System",
    role: "Automated",
    action: "DRIFT_DETECTED",
    target: "TM-4482",
    module: "Trademark",
    hash: "d1e8c94a",
    outcome: "flagged",
    notes: "Identity anchor mismatch found. Alert ALT-9921 triggered.",
  },
  {
    id: "CDX-00439",
    timestamp: "2026-05-11 08:55:31",
    actor: "Marcus Chen",
    role: "Ops Admin",
    action: "TASK_RESOLVED",
    target: "OPS-8812",
    module: "Operations",
    hash: "7b4d20f1",
    outcome: "success",
    notes: "Escalation closed — compliance handoff completed.",
  },
  {
    id: "CDX-00438",
    timestamp: "2026-05-11 08:12:00",
    actor: "Lydia Martins",
    role: "Compliance Officer",
    action: "EXCEPTION_REVIEWED",
    target: "CON-4477",
    module: "Consent",
    hash: "5c3a11b8",
    outcome: "success",
    notes: "Renewal exception granted. New expiry 2026-09-01.",
  },
  {
    id: "CDX-00437",
    timestamp: "2026-05-10 17:44:22",
    actor: "D. Farouk",
    role: "Ops Admin",
    action: "PROMOTION_BLOCKED",
    target: "TM-7741",
    module: "Trademark",
    hash: "e2f7a930",
    outcome: "blocked",
    notes: "Insufficient privileges. Requires Trust Admin approval.",
  },
  {
    id: "CDX-00436",
    timestamp: "2026-05-10 15:30:10",
    actor: "Sarah Okonkwo",
    role: "Trust Admin",
    action: "ROLE_UPDATED",
    target: "USR-1021",
    module: "Admin",
    hash: "9a1d53e4",
    outcome: "success",
    notes: "View-only → Ops Admin elevation approved.",
  },
  {
    id: "CDX-00435",
    timestamp: "2026-05-10 14:02:45",
    actor: "System",
    role: "Automated",
    action: "CONSENT_EXPIRY_ALERT",
    target: "CON-2281",
    module: "Consent",
    hash: "b7c2e104",
    outcome: "flagged",
    notes: "48-hour expiry warning. Alert ALT-9920 created.",
  },
  {
    id: "CDX-00434",
    timestamp: "2026-05-10 11:20:09",
    actor: "Marcus Chen",
    role: "Ops Admin",
    action: "RECORD_INTAKE",
    target: "CON-4390",
    module: "Consent",
    hash: "c8f4a712",
    outcome: "success",
    notes: "New draft record created. Pending Trust Admin assignment.",
  },
];

// ─── Operations Tasks ──────────────────────────────────────────────────────────

export const operationsTasks = [
  {
    id: "OPS-8820",
    title: "Renew consent window for GV-2281",
    priority: "urgent",
    status: "in-progress",
    assignee: "Marcus Chen",
    due: "2026-05-13",
    module: "Consent",
    linkedAlert: "ALT-9920",
  },
  {
    id: "OPS-8819",
    title: "Remediate drift — TM Registry #4482",
    priority: "urgent",
    status: "open",
    assignee: "Unassigned",
    due: "2026-05-12",
    module: "Trademark",
    linkedAlert: "ALT-9921",
  },
  {
    id: "OPS-8818",
    title: "Update policy references — Compliance v3 deprecated",
    priority: "high",
    status: "open",
    assignee: "Lydia Martins",
    due: "2026-05-15",
    module: "Compliance",
    linkedAlert: "ALT-9918",
  },
  {
    id: "OPS-8815",
    title: "Review role escalation — D. Farouk",
    priority: "medium",
    status: "reviewing",
    assignee: "Sarah Okonkwo",
    due: "2026-05-14",
    module: "Admin",
    linkedAlert: "ALT-9914",
  },
  {
    id: "OPS-8810",
    title: "Conduct quarterly audit readiness sweep",
    priority: "medium",
    status: "in-progress",
    assignee: "Lydia Martins",
    due: "2026-05-20",
    module: "Compliance",
    linkedAlert: null,
  },
  {
    id: "OPS-8806",
    title: "Promote NovaBridge compliance record v2.3",
    priority: "low",
    status: "open",
    assignee: "Marcus Chen",
    due: "2026-05-22",
    module: "Consent",
    linkedAlert: null,
  },
  {
    id: "OPS-8801",
    title: "Archive expired Ascend Realty trust agreement",
    priority: "low",
    status: "done",
    assignee: "Marcus Chen",
    due: "2026-05-10",
    module: "Consent",
    linkedAlert: null,
  },
];

// ─── Users ─────────────────────────────────────────────────────────────────────

export const users = [
  {
    id: "USR-1001",
    name: "Sarah Okonkwo",
    email: "s.okonkwo@org.internal",
    role: "Trust Admin",
    status: "active",
    lastLogin: "2026-05-11 09:41",
    actions30d: 312,
    avatar: "SO",
    color: "amber",
  },
  {
    id: "USR-1002",
    name: "Marcus Chen",
    email: "m.chen@org.internal",
    role: "Ops Admin",
    status: "active",
    lastLogin: "2026-05-11 08:55",
    actions30d: 528,
    avatar: "MC",
    color: "cyan",
  },
  {
    id: "USR-1003",
    name: "Lydia Martins",
    email: "l.martins@org.internal",
    role: "Compliance Officer",
    status: "active",
    lastLogin: "2026-05-11 08:12",
    actions30d: 210,
    avatar: "LM",
    color: "emerald",
  },
  {
    id: "USR-1004",
    name: "D. Farouk",
    email: "d.farouk@org.internal",
    role: "Ops Admin",
    status: "restricted",
    lastLogin: "2026-05-10 17:44",
    actions30d: 44,
    avatar: "DF",
    color: "rose",
  },
  {
    id: "USR-1021",
    name: "Jin Park",
    email: "j.park@org.internal",
    role: "View-only",
    status: "active",
    lastLogin: "2026-05-09 14:00",
    actions30d: 0,
    avatar: "JP",
    color: "violet",
  },
  {
    id: "USR-1022",
    name: "R. Alvarez",
    email: "r.alvarez@auditors.ext",
    role: "View-only",
    status: "active",
    lastLogin: "2026-05-07 11:30",
    actions30d: 0,
    avatar: "RA",
    color: "violet",
  },
];

// ─── Trademark Records ─────────────────────────────────────────────────────────

export const trademarkRecords = [
  {
    id: "TM-4482",
    name: "MERIDIAN HEALTH™",
    class: "Class 44 — Medical Services",
    jurisdiction: "USPTO / EU",
    status: "drift-flagged",
    registered: "2021-04-10",
    expires: "2031-04-09",
    licensee: "Meridian Health Group",
    owner: "Sarah Okonkwo",
  },
  {
    id: "TM-4480",
    name: "VANTARA ROUTE™",
    class: "Class 39 — Transport",
    jurisdiction: "USPTO",
    status: "active",
    registered: "2022-01-22",
    expires: "2032-01-21",
    licensee: "Vantara Logistics Ltd",
    owner: "Marcus Chen",
  },
  {
    id: "TM-7741",
    name: "KESTREL MARK™",
    class: "Class 36 — Finance",
    jurisdiction: "UKIPO",
    status: "draft",
    registered: "—",
    expires: "—",
    licensee: "Kestrel Finance",
    owner: "Unassigned",
  },
  {
    id: "TM-4411",
    name: "NOVABRIDGE SYS™",
    class: "Class 42 — Technology",
    jurisdiction: "USPTO / CA",
    status: "active",
    registered: "2020-08-05",
    expires: "2030-08-04",
    licensee: "NovaBridge Corp",
    owner: "Marcus Chen",
  },
];
